name: CI Calculadora React

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências e buildar
        run: |
          npm install
          npm run build
